import type { Metadata } from 'next';
import PageShell from '@/components/PageShell';

export const metadata: Metadata = {
  title: 'Sources — Clinicle',
  description:
    'Data sources, models, and prior work that Clinicle builds on.',
};

export default function SourcesPage() {
  return (
    <PageShell eyebrow="Credits" title="Sources">
      <h2>Semantic model</h2>
      <ul>
        <li>
          Fangyu Liu, Ehsan Shareghi, Zaiqiao Meng, Marco Basaldella, Nigel
          Collier. <em>Self-Alignment Pretraining for Biomedical Entity
          Representations.</em> NAACL 2021. —{' '}
          <a
            href="https://arxiv.org/abs/2010.11784"
            target="_blank"
            rel="noopener noreferrer"
          >
            arXiv:2010.11784
          </a>
        </li>
        <li>
          Model weights:{' '}
          <a
            href="https://huggingface.co/cambridgeltl/SapBERT-from-PubMedBERT-fulltext"
            target="_blank"
            rel="noopener noreferrer"
          >
            cambridgeltl/SapBERT-from-PubMedBERT-fulltext
          </a>{' '}
          on Hugging Face.
        </li>
      </ul>

      <h2>Terminology</h2>
      <ul>
        <li>
          Unified Medical Language System (UMLS) — U.S. National Library of
          Medicine.
        </li>
        <li>
          MedlinePlus and public disease compendia for the diagnosis short
          list.
        </li>
      </ul>

      <h2>Prior art</h2>
      <ul>
        <li>
          <a
            href="https://semantle.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            Semantle
          </a>{' '}
          by David Turner — the game format Clinicle borrows from.
        </li>
        <li>
          <a
            href="https://www.nytimes.com/games/wordle/index.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Wordle
          </a>{' '}
          — the daily-puzzle cadence.
        </li>
      </ul>

      <h2>Prompts</h2>
      <p>
        Daily flavor prompts are generated by an LLM under a system prompt
        that forbids naming the diagnosis or an unambiguous eponym, then
        committed to the repo. If a prompt ever reads as unfair, please let
        us know on the feedback page.
      </p>
    </PageShell>
  );
}
